'use strict';

const fs = require('fs');
const path = require('path');

/*
 * properties.js — read/write a Java `.properties` file (server.properties)
 * without losing comments or key order. We keep the file as a list of lines and
 * an index of which line holds each key, so edits are surgical.
 */

function parse(text) {
  const lines = String(text).split(/\r?\n/);
  const keys = [];        // key order
  const index = {};       // key -> line number
  const values = {};      // key -> value
  lines.forEach((line, i) => {
    const m = line.match(/^([^#!=:\s][^=:]*)[=:](.*)$/);
    if (m) {
      const key = m[1].trim();
      values[key] = m[2];
      index[key] = i;
      keys.push(key);
    }
  });
  return { lines, keys, index, values };
}

function serialize(model) {
  return model.lines.join('\n');
}

function set(model, key, value) {
  if (key in model.index) {
    const i = model.index[key];
    model.lines[i] = `${key}=${value}`;
  } else {
    model.lines.push(`${key}=${value}`);
    model.index[key] = model.lines.length - 1;
    model.keys.push(key);
  }
  model.values[key] = value;
}

function load(dir) {
  const file = path.join(dir, 'server.properties');
  try {
    return { file, model: parse(fs.readFileSync(file, 'utf8')) };
  } catch {
    return { file, model: parse('') };
  }
}

function save(file, model) {
  fs.writeFileSync(file, serialize(model));
}

// A sensible default server.properties for a freshly created server, with the
// fields the wizard cares about already set.
function defaults({ port = 25565, motd = 'A yasc-managed server' } = {}) {
  return [
    '#Minecraft server properties',
    '#Generated by yasc',
    `motd=${motd}`,
    `server-port=${port}`,
    'gamemode=survival',
    'difficulty=easy',
    'max-players=20',
    'online-mode=true',
    'pvp=true',
    'spawn-protection=16',
    'view-distance=10',
    'simulation-distance=10',
    'allow-nether=true',
    'enable-command-block=false',
    'white-list=false',
    'level-name=world',
    'level-seed=',
    'enable-rcon=false',
  ].join('\n') + '\n';
}

module.exports = { parse, serialize, set, load, save, defaults };
